#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     WarpDrive1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     WarpDrive2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     RightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     LeftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     Sweeper1,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     Sweeper2,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define WARPDRIVE1 "WarpDrive1"
#define WARPDRIVE2 "WarpDrive2"
#define DRIVELEFT "Y1"
#define DRIVERIGHT "Y2"
#define LEFTBACK "LeftBack"
#define RIGHTBACK "RightBack"
#define FIRE1 "LB/5"
#define FIRE2 "RB/6"
#define SWEEPER1 "Sweeper1"
#define SWEEPER2 "Sweeper2"



task main()
{

	//The do should allow for the program to repeat
	do
	{
		//setting up the main launcher, if both fire buttons are pressed,
		//it will reverse for the purpose of clearing the mechanism

		//I need to slow down the speed before switching direction

		while(FIRE1 == true && FIRE2 == true)
		{
			motor[WARPDRIVE1] = -100;
			motor[WARPDRIVE2] = -100;
			if(while == false)
			{
				break;
			}
			EndTimeSlice();
		}
		while(FIRE1 == false && FIRE2 = false)
		{
			motor[WARPDRIVE1] = 100;
			motor[WARPDRIVE2] = 100;
			if(while == false)
			{
				break;
			}

			EndTimeSlice();
		}








		//This the drive function for the left wheels

		//While the joystick is over 80, the left motors will go 100
		if((DRIVELEFT >= 80))
		{

			motor[LEFTBACK] = 100;
			EndTimeSlice();
		}

		//While the joystick is bellow 80, the left side will go 50
		if((DRIVELEFT <80 && DRIVELEFT >25))
		{


			motor[LEFTBACK] = 50;

			EndTimeSlice();
		}

		//This the backwards drive function for the left wheels

		//While the joystick is under -80, the left motors will go -100
		if((DRIVELEFT <= -80))
		{

			motor[LEFTBACK] = -100;
			EndTimeSlice();

		}

		//While the joystick is over -50, the left side will go -50
		if((DRIVELEFT >-80 && DRIVELEFT <-25))
		{


			motor[LEFTBACK] = -50;
			EndTimeSlice();
		}



		//Drive function for the right side

		//While the joystick os above 50, the right side will go 100
		if((DRIVERIGHT >= 80))
		{

			motor[RIGHTBACK] = 100;
			EndTimeSlice();
		}

		//While the joystick is bellow 50, the right side will go 50
		if((DRIVERIGHT <80 && DRIVERIGHT >25))
		{
			motor[RIGHTBACK] = 50;
			EndTimeSlice();
		}



		//Backwards drive function for the right side

		//While the joystick os bellow -50, the right side will go -100
		if((DRIVERIGHT <= -80))
		{

			motor[RIGHTBACK] = -100;
			EndTimeSlice();
		}

		//While the joystick is above -50, the right side will go -50
		if((DRIVERIGHT > -80 && DRIVERIGHT <25))
		{

			motor[RIGHTBACK] = -50;

			EndTimeSlice();
		}

		//this is the control for the sweepers


		while(FIRE1 == true && FIRE2 == true)
		{
			motor[SWEEPER1] = -100;
			motor[SWEEPER2] = -100;
			if("while == false")
			{
				break;
			}
			EndTimeSlice();
		}
		while(FIRE1 = false && FIRE2 = false)
		{
			motor[SWEEPER1] = 100;
			motor[SWEEPER2] = 100;

			if(while == true)
			{	break;

			}
			EndTimeSlice();
		}



	}
	// This is the end of the initial do...While statement
	while (true);
}
