#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Warpdrive1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Warpdrive2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     Motorleftfront, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     Motorleftback, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Motorrightfront, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Motorrightback, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main()
{


	while(true)
{

		motor[mtr_S1_C1_1] =	100;
		motor[mtr_S1_C1_2] =	100;

		EndTimeSlice()
	}
		}
